x86: irq_pipeline: add IRQ pipeline core
Signed-off-by: Philippe Gerum <rpm@xenomai.org>
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

x86: dovetail: Fix Intel shadow stack support

Let fpregs_lock_and_load return the saved flags of fpregs_lock and make
sure that the shadow stack callers use that properly.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

x86: irq_pipeline: Raise oob IPIs only for the requested cpumask

irq_send_oob_ipi() silently migrates from the supplied cpumask to
allbutself, which is a overkill - especially for the OOB resched
vector.

Seen in a real world trace - cpumask=6 requested but each CPU got one:

       SCTSeqRun-17771 [000]  5888.449485: ipi_send_cpumask:     cpumask=6 callsite=run_oob_call+0x91 callback=0x0
       SCTSeqRun-17771 [000]  5888.449487: write_msr:            830, value c00ea
   OMP-TT-P19511-22125 [021]  5888.449489: irq_pipeline_entry:   irq=524545
 PARC92.rawobjpr-19511 [019]  5888.449489: irq_pipeline_entry:   irq=524545
       SCTSeqRun-17771 [000]  5888.449489: cobalt_head_sysexit:  result=0
              ps-23075 [018]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22138 [004]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22129 [024]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22131 [013]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22147 [011]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22128 [010]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22137 [003]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22144 [001]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22145 [005]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22140 [015]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22136 [014]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22134 [007]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22121 [012]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22127 [009]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22130 [025]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22149 [008]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22148 [002]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22122 [028]  5888.449489: irq_pipeline_entry:   irq=524545
   OMP-TT-P19511-22126 [027]  5888.449489: irq_pipeline_entry:   irq=524545
   ...

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>

x86: dovetail: Fix inverted debug check in lock_vector_lock

Code and comment were not in line, but the comment actually makes more
sense here, given that unlock_vector_lock will unconditionally reenable
hard IRQs.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

x86: irq_pipeline: Use appropriate EOI on error interrupts

Just like for the non-pipelined spurious interrupt, we need to invoke
the non-pipelined __apic_eoi while handling error interrupts. Otherwise,
the local APIC will stop receiving further interrupts, and the system
will stall.

Given that it takes very special conditions to actually trigger an error
interrupt, this issue was very likely not relevant for most deployments.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

x86: irq_pipeline: Fix build failure for !IRQ_PIPELINE but X86_FRED

The POSTED_MSI_NOTIFICATION_VECTOR is present since 6.10, so
FIRST_SYSTEM_APIC_VECTOR was off by one resulting in the following build
warning:

./arch/x86/include/asm/irq_vectors.h:104:41: error: array index in initializer exceeds array bounds
  104 | #define POSTED_MSI_NOTIFICATION_VECTOR  0xeb
      |                                         ^~~~
arch/x86/entry/entry_fred.c:98:37: note: in definition of macro ‘SYSVEC’
   98 | #define SYSVEC(_vector, _function) [_vector - FIRST_SYSTEM_VECTOR] = fred_sysvec_##_function
      |                                     ^~~~~~~
arch/x86/entry/entry_fred.c:121:16: note: in expansion of macro ‘POSTED_MSI_NOTIFICATION_VECTOR’
  121 |         SYSVEC(POSTED_MSI_NOTIFICATION_VECTOR,  posted_msi_notification),
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/irq_vectors.h:104:41: note: (near initialization for ‘sysvec_table’)
  104 | #define POSTED_MSI_NOTIFICATION_VECTOR  0xeb
      |                                         ^~~~
arch/x86/entry/entry_fred.c:98:37: note: in definition of macro ‘SYSVEC’
   98 | #define SYSVEC(_vector, _function) [_vector - FIRST_SYSTEM_VECTOR] = fred_sysvec_##_function
      |                                     ^~~~~~~
arch/x86/entry/entry_fred.c:121:16: note: in expansion of macro ‘POSTED_MSI_NOTIFICATION_VECTOR’
  121 |         SYSVEC(POSTED_MSI_NOTIFICATION_VECTOR,  posted_msi_notification),
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Required build configuration:
  - CONFIG_IRQ_PIPELINE = n
  - CONFIG_X86_FRED = y

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>

kernel/entry: irq_pipeline: Do not leave .noinstr.text section

Fixing the following warning by moving the call to irqentry_syncstage()
into a instrumentation_begin() section.

vmlinux.o: warning: objtool: irqentry_exit+0xab: call to synchronize_pipeline() leaves .noinstr.text section

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>