x86: Temporary fix for upstream build problem
Upstream commit
0701c9e17bd9 ("x86/kvm/vmx: Move IRQ/NMI dispatch from KVM into x86 core")
introduced a build failure:

arch/x86/entry/common.c: In function ‘x86_entry_from_kvm’:
arch/x86/entry/common.c:27:17: error: implicit declaration of function ‘fred_entry_from_kvm’; did you mean ‘idt_entry_from_kvm’? [-Wimplicit-function-declaration]
   27 |                 fred_entry_from_kvm(event_type, vector);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 idt_entry_from_kvm
arch/x86/entry/common.c:50:24: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]
   50 |                 return fred_entry_from_kvm(event_type, vector);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/x86/entry/common.c:18:14: note: declared here
   18 | noinstr void x86_entry_from_kvm(unsigned int event_type, unsigned int vector)

Problem has been reported, should hopefully be fixed soon.

Signed-off-by: Florian Bezdeka <florian.bezdeka@siemens.com>